### ISSUE TITLE
Build complete notification emails contain JSON data

### ISSUE THREAD

**Issue by tomhughes** [fedora-infra/fmn#646] opened 2022-11-09 20:51 UTC
The build complete notification emails seem to have started including a big chunk of JSON data, for example:

```
Notification time stamped 2022-11-09 20:12:06 UTC

{
    "certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUyakNDQkVPZ0F3SUJBZ0lDQXBzd0RRWUpL\nb1pJaHZjTkFRRUxCUUF3Z2FBeEN6QUpCZ05WQkFZVEFsVlQKTVFzd0NRWURWUVFJRXdKT1F6RVFN\nQTRHQTFVRUJ4TUhVbUZzWldsbmFERVhNQlVHQTFVRUNoTU9SbVZrYjNKaApJRkJ5YjJwbFkzUXhE\nekFOQmdOVkJBc1RCbVpsWkcxelp6RVBNQTBHQTFVRUF4TUdabVZrYlhObk1ROHdEUVlEClZRUXBF\nd1ptWldSdGMyY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV2x1UUdabFpHOXlZWEJ5YjJwbFkz\nUXUKYjNKbk1CNFhEVEU0TURreU5qSXpNalV3T0ZvWERUSTRNRGt5TXpJek1qVXdPRm93Z2VReEN6\nQUpCZ05WQkFZVApBbFZUTVFzd0NRWURWUVFJRXdKT1F6RVFNQTRHQTFVRUJ4TUhVbUZzWldsbmFE\nRVhNQlVHQTFVRUNoTU9SbVZrCmIzSmhJRkJ5YjJwbFkzUXhEekFOQmdOVkJBc1RCbVpsWkcxelp6\nRXhNQzhHQTFVRUF4TW9abVZrYlhObkxXMXAKWjNKaGRHbHZiaTEwYjI5c2N5NW1aV1J2Y21Gd2Nt\nOXFaV04wTG05eVp6RXhNQzhHQTFVRUtSTW9abVZrYlhObgpMVzFwWjNKaGRHbHZiaTEwYjI5c2N5\nNW1aV1J2Y21Gd2NtOXFaV04wTG05eVp6RW1NQ1FHQ1NxR1NJYjNEUUVKCkFSWVhZV1J0YVc1QVpt\nVmtiM0poY0hKdmFtVmpkQzV2Y21jd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dn\nRUtBb0lCQVFEUm4xd1E1UVZwN2JCdUpFUjlNOUkwZ2o0WHB0NTlFZDdnU1p2RVQvcSsrUVNFb0x2\nWApkb0tnOTdkWXhZK2FPdll1TDAzc1lOdjZEcmJLZVM2blk5V1dwKytoZ1hUMXBEaFY3QmRxeitt\nNFoxbDhsYjFHCi9mZHAwd1FON0RMVndDclYyTmNSajZ6b2J0NHV2Z0JYaWtVUWhRNjl5V2E2VE9D\nTis5OWEwUUtjTUJzNENuNTAKc2pmUTNGQUNsV1B3NUhkNkNPMHJWenhPODRROGc0bEpCcTRubHY0\nc0xRVmZoZTNoZWMzTEFObUt2RGNSc3JpbgpDUXFGdFF5MVNmR0pHWnE4RkEyUDhkckVCd1BqdnZx\nMTJ4MHJucEJjdVM5bXlLQmhOYVE3eSs5bE9GTXJSZFBrCmRaUXY0eGdSU0FzZGJQRDlyeXYrTE1n\nS1YvVnVTdm11RzF0eEFnTUJBQUdqZ2dGWE1JSUJVekFKQmdOVkhSTUUKQWpBQU1DMEdDV0NHU0FH\nRytFSUJEUVFnRmg1RllYTjVMVkpUUVNCSFpXNWxjbUYwWldRZ1EyVnlkR2xtYVdOaApkR1V3SFFZ\nRFZSME9CQllFRkM0anZCbmhFSnRDTkxHaTg5UHgreU41K1VNa01JSFZCZ05WSFNNRWdjMHdnY3FB\nCkZHdEFXdmtTQ0lsWjUxbmxCZlVDSFFwT2Z4UUFvWUdtcElHak1JR2dNUXN3Q1FZRFZRUUdFd0pW\nVXpFTE1Ba0cKQTFVRUNCTUNUa014RURBT0JnTlZCQWNUQjFKaGJHVnBaMmd4RnpBVkJnTlZCQW9U\nRGtabFpHOXlZU0JRY205cQpaV04wTVE4d0RRWURWUVFMRXdabVpXUnRjMmN4RHpBTkJnTlZCQU1U\nQm1abFpHMXpaekVQTUEwR0ExVUVLUk1HClptVmtiWE5uTVNZd0pBWUpLb1pJaHZjTkFRa0JGaGRo\nWkcxcGJrQm1aV1J2Y21Gd2NtOXFaV04wTG05eVo0SUoKQU9OUUhrZFBGeDVGTUJNR0ExVWRKUVFN\nTUFvR0NDc0dBUVVGQndNQ01Bc0dBMVVkRHdRRUF3SUhnREFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9C\nZ1FBQnFBcDQzd3lUbk5XUUJYODUzSEVEUEpDTTM4aVJTdlV3dzFCejd4MmFpSWpuCkVPTWZ1djhB\nTEV2Z2JXeDhSc0RBNTluRkNXS1FJRWdGeEFBcUFMUFJwYWF3dFRUcnN1VlQ3bFhlSEhrU21VblEK\ncEdKSFd1elU2OUZibFdaWkpDTVQzUTRVYWNUa0VHNE1XMFFqOWp1aFNpM2lHOHZXVXZlMTEzUTNL\nMDhmVHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\n",
    "crypto": "x509",
    "i": 4658458,
    "msg": {
        "attribute": "state",
        "build_id": 2086486,
        "epoch": null,
        "instance": "primary",
        "name": "pyosmium",
        "new": 1,
        "old": 0,
        "owner": "tomh",
        "release": "1.fc38",
        "request": [
            "git+https://src.fedoraproject.org/rpms/pyosmium.git#db83a3f1c6ee1a28698193f7c8765142c57c0060",
            "rawhide",
            {}
        ],
        "task_id": 93984529,
        "version": "3.5.0"
    },
    "msg_id": "2022-5df52e1b-6ed8-4d4a-9999-7a26c9c5b592",
    "signature": "AMxQogeXEHmNCnHb6imkefQHw1fn7gJ6BtKB0aQ8fxKrdcbsABLSh/OhUANjvECNiMI7C+b/PV4D\nsyYJTJCTXoGJ5kddDDvr1kjMciwXTm2jj94tV6uqhKrWxhLlC7RMDk8D8/I9WnfeUj0nGeE+vMwR\n7dom2iTvlcib+QkLGuEIwU3u8Aa17UrI8hOh/dK6B+eLleSAEq0Vvtruw/k2Lwk7lS57IrsPndai\nTTiog8mOBC316G/oBWCzuLd1jVyoB9ZRk7Ht3DG7+aZH65yviW2Ixjjb0dqQEZhAF8eMeu4gZCjj\nWitOAZqWSs6WYLqfDsHUIS0JsgK4YIIwW/vNKA==\n",
    "timestamp": 1668024726,
    "topic": "org.fedoraproject.prod.buildsys.build.state.change",
    "username": "amqp-bridge"
}
	http://koji.fedoraproject.org/koji/buildinfo?buildID=2086486
```

**Comment by ryanlerch** [comment] 2023-02-27 02:46
Duplicate of #633

**Closed as completed** 2023-02-27 02:54 UTC
Labels: fmn-old
