### ISSUE TITLE
No notifications sent for koji builds where srpm building fails

### ISSUE THREAD

**Issue by kalev** [fedora-infra/fmn#87] opened 2015-04-19 11:10 UTC
See e.g. http://koji.fedoraproject.org/koji/taskinfo?taskID=9512811 where the buildSRPMFromSCM task failed. I got no notification for that.

**Comment by jeremycline** [comment] 2016-11-30 17:22
This looks like a duplicate of #62

**Closed as completed by jeremycline** 2016-11-30 17:22 UTC
