### ISSUE TITLE
I'm not Kevin kofler (I think?)

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/fmn#33] opened 2014-10-26 16:01 UTC
I've received 3 messages from FMN lately, and I have no clue why I'm receiving them.

```
buildsys.build.state.change -- kkofler's qt5-qttools-5.4.0-0.2.beta.fc22 started building http://koji.fedoraproject.org/koji/buildinfo?buildID=587810

--
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications//bochecha.id.fedoraproject.org/email/10058
```

```
git.receive -- kkofler pushed to clucene09 (master).  "Fix uninitialized read in Lexer::ReadEscape (..more)" http://pkgs.fedoraproject.org/cgit/clucene09.git/commit/?h=master&id=1cf69ff0f6bb18eec58ec5d93088038dbb68d50e

--
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications//bochecha.id.fedoraproject.org/email/10059
```

```
buildsys.build.state.change -- kkofler's phonon-backend-gstreamer-4.8.0-3.fc22 completed http://koji.fedoraproject.org/koji/buildinfo?buildID=587760

-- 
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications//bochecha.id.fedoraproject.org/email/10058
```

**Comment by ralphbean** [comment] 2014-10-26 19:09
Can you share any information about the filters defined under email/10058 and email/10059?

**Comment by bochecha** [comment] 2014-10-27 08:45
Absolutely. :smiley: 
- email/10058 has 3 rules:
  - Koji: build changed state (started, failed, finished)
  - All messages concerning user's packages (for my fas nick: bochecha)
  - Koji: pertains only to particular instances (only for the primary instance)
- email/10059 has 2 rules:
  - Git: Changes have been pushed onto the git of a package
  - All messages concerning user's packages (for my fas nick: bochecha)

**Comment by ralphbean** [comment] 2014-10-27 12:15
Weird.  I have no clue how this happened, but will think about it.

**Comment by bochecha** [comment] 2015-01-08 15:57
It also happens in the webapp.

If I login to https://apps.fedoraproject.org/notifications/ then select a filter, for example "_Bodhi comments on my packages_", then on the filter page, in the list of messages matching this filter, I see for example:

[40 minutes ago](https://admin.fedoraproject.org/updates/duplicity-0.6.24-4.el7) kiven commented on bodhi update duplicity-0.6.24-4.el7 (karma: 1) 

As far as I can see, I have no relationship with this package: https://admin.fedoraproject.org/pkgdb/package/duplicity/

**Comment by ralphbean** [comment] 2015-01-08 19:10
The webapp portion is much easier to debug than the email portion since I can recreate the scenario and study it.

I went to do that today, and could duplicate the exact same situation.  I _too_ had the "[40 minutes ago](https://admin.fedoraproject.org/updates/duplicity-0.6.24-4.el7) kiven commented on bodhi update duplicity-0.6.24-4.el7 (karma: 1)" message in my list.

As I dug into why it was happening, I noticed that the cache layer wasn't configured at all on the webapp ( a months-long mistake).  I fixed that, but then couldn't reproduce the bug anymore.

If you can't reproduce it either, @bochecha then I want to close this one.

**Comment by bochecha** [comment] 2015-01-09 08:29
Well, now I get absolutely no messages matching this filter (or others) in the web UI :confused:

**Closed as completed** 2015-01-09 18:36 UTC
