### ISSUE TITLE
new fmn does not support koschei events

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/fmn#915] opened 2023-06-02 14:14 UTC
As a packager and SIG group member, some of the most important notifications I'm currently getting from the old notifications system are when a package that I'm associated with starts to fail to build (i.e. koschei events). Reacting to these FailsToBuildFromSource / FailsToInstall issues in a timely manner is important, since failure to act can result in package ownership being lost.

**Comment by penguinpee** [comment] 2023-06-20 00:08
I was just looking to setup something along the same lines for NeuroFedora SIG packages. I guess the fix will be in the next release. Is there an eta when Koschei messages will be available in FMN?

**Comment by mizdebsk** [comment] 2023-06-28 13:38
New Koschei production deployment is planned in early July. It will contain required changes on Koschei side.
But I have no idea when required FMN changes will be committed and deployed.

**Comment by abompard** [comment] 2023-09-08 07:39
Actually, FMN already contains the Koschei schemas, so this should be working now. Could you verify please, @decathorpe ?

**Comment by decathorpe** [comment] 2023-09-08 07:44
Can confirm that koschei is now available in the list of applications. I'll try to create a rule to see if it's working.

**Comment by decathorpe** [comment] 2023-09-12 09:28
I set up some rules with koschei messages, but I don't seem to get any messages from it. Have the changes that are required on the koschei side been deployed yet?

**Comment by abompard** [comment] 2023-09-12 09:39
According to Datagrepper, Koschei seems to still be sending the messages without the schema:
```
$ http get https://apps.fedoraproject.org/datagrepper/raw category==koschei | json_reformat | grep fedora_messaging_schema
               "fedora_messaging_schema": "base.message",
[...]
```

**Comment by mizdebsk** [comment] 2023-09-18 06:36
> Have the changes that are required on the koschei side been deployed yet?

Not yet. For now the changes have been deployed only in staging. I'll try to deploy them in production within next few days.

**Comment by abompard** [comment] 2024-01-04 12:08
Hey @mizdebsk , any news on that?

**Comment by decathorpe** [comment] 2024-04-20 17:25
*ping* not sure if this has been deployed or not, but it's still not working.

**Comment by mizdebsk** [comment] 2024-06-10 12:01
Koschei changes have been deployed to production on 5 July 2024.
Since then I can see Koschei messages in datagrepper with fedora_messaging_schema set,
for example https://apps.fedoraproject.org/datagrepper/v2/id?id=e9137fa8-f3aa-4b81-9e8b-ad443e8ad240&size=extra-large

**Comment by voxik** [comment] 2024-06-10 12:05
I can confirm I have started to receive email notifications 👍

**Comment by decathorpe** [comment] 2024-06-10 12:09
I have started receiving messages on Matrix too, but it looks like I'm only getting about "started to fail resolving dependencies" and "dependencies resolve OK again", but not "package started to fail to build".

**Comment by voxik** [comment] 2024-06-10 13:02
I have received email notifications such as "[Koschei] rubygem-connection_pool's builds started to fail in f41"

**Comment by oturpe** [comment] 2024-10-27 19:41
Looking at [this Fedora devel thread](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RUTIS3MUFEK2F5YFPDMY2BNMNY46P5QW/), it seems that there is no way, or at least no way that it known in the devel mailing list, to get notifications from all packages where I am a co-maintainer. This is not good, having co-maintainers is much less useful if they are cut off from important events like Koschei build failures.

**Comment by decathorpe** [comment] 2024-10-27 23:44
FWIW, I have configured notifications.fp.o to send me koschei notifications in every possible way (My Events, Events associated with my FAS user, events associated for all SIG groups I am member of), and I have received less than 10 notifications in all of October,  with the last notification being two weeks old, and there were definitively events that happened since. So something is definitely not working as inteneded, but I can't really tell what or how.

**Comment by abompard** [comment] 2024-10-28 15:33
> Looking at [this Fedora devel thread](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RUTIS3MUFEK2F5YFPDMY2BNMNY46P5QW/), it seems that there is no way, or at least no way that it known in the devel mailing list, to get notifications from all packages where I am a co-maintainer. This is not good, having co-maintainers is much less useful if they are cut off from important events like Koschei build failures.

According to [the get_project_users()](https://github.com/fedora-infra/fmn/blob/fde094ce6f285e1dcd657f235c3f3bf9dbd5267e/fmn/backends/pagure.py#L137) function, you should be notified if you have a Pagure role in "owner", "admin", "commit", "collaborator". I see you have the "admin" role in `tilix`, so you should have been notified.
When I look at tilix's status in Koschei, it seems that the build that change tilix's status was [build 18872255](https://koschei.fedoraproject.org/build/18872255) that was done at 2024-10-10 03:14:50 and which resulted in [this message](https://apps.fedoraproject.org/datagrepper/v2/id?id=de733dfa-dfd2-4c87-a219-dab48620cb13&is_raw=true&size=extra-large). The message seems correct so yeah, you should have received a notification.

I can try to look into the logs but it's not easy because the event happened 18 days ago, and we have a ton of logs. Could you open a ticket if it happens again please?

**Comment by decathorpe** [comment] 2024-10-28 15:48
I have two examples from today, if that helps:

https://koschei.fedoraproject.org/package/rust-quinn?collection=epel9-next
https://koschei.fedoraproject.org/package/rust-sequoia-openpgp?collection=f41

Both started to fail to build (due to an ongoing flakiness issue with ppc64le builders as far as I can tell) within the last few hours.

But I have not received any notifications from koschei since October 16.

**Comment by abompard** [comment] 2024-10-29 08:15
OK, after a little investigation I think the problem comes from the cache. It takes a while to rebuild (more than an hour) and sometimes Pagure's API stops responding, and I think we're not handling that well. I'll keep digging.

**Comment by abompard** [comment] 2024-10-30 08:25
OK I've increased the amount of attempts we retry to query Pagure when its API returns 500 from 3 to 10, but of course it brings the cache rebuild time from a bit more than an hour to about 8 hours, which seems too big. I'll need to find a balance.
And of course, the queries on which Pagure's API does not respond are those for users that have the most packages (I can clearly see the timeouts in Pagure's log), which also mean that it's the queries that have the most impact on FMN's work.
I'll increase Pagure's timeout for now (it's currently at 60 seconds) but I don't think it's a good solution. If you have ideas (besides speeding up the Pagure replacement project), I'm interested.

**Comment by abompard** [comment] 2024-10-30 08:30
Anyway, I'll open a new ticket, because this is unrelated to koschei.

**Closed as completed** 2024-10-30 08:37 UTC
