### ISSUE TITLE
I'm getting spammed with taskotron results by a DISABLED askbot filter

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#245] opened 2017-10-26 08:13 UTC
I've created the following filter:
https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/53899/
```
All messages matching a regular expression 
  pattern  (taskotron|Taskotron|autoqa|Autoqa|AutoQA|autoQA|openqa|Openqa|openQA|OpenQA) 
All askbot events
```
and I'm getting all taskotron results:
```
<fedora-notif> taskotron.result.new -- dist.python-versions.executables PASSED for pacemaker-1.1.18-0.1.rc3.fc28.2 5 minutes ago https://taskotron.fedoraproject.org/artifacts/all/d04349b4-ba22-11e7-9ab3-525400817a8f    ( triggered by https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/53899 )
<fedora-notif> taskotron.result.new -- dist.rpmgrill.spec-file-sanity FAILED for pacemaker-1.1.18-0.1.rc3.fc28.2 5 minutes ago https://taskotron.fedoraproject.org/artifacts/all/d0353112-ba22-11e7-8950-525400817a8f/task_output/rpmgrill.json    ( triggered by https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/53899 )
<fedora-notif> taskotron.result.new -- dist.rpmgrill.multilib PASSED for pacemaker-1.1.18-0.1.rc3.fc28.2 5 minutes ago https://taskotron.fedoraproject.org/artifacts/all/d0353112-ba22-11e7-8950-525400817a8f/task_output/rpmgrill.json    ( triggered by https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/53899 )
<fedora-notif> taskotron.result.new -- dist.rpmgrill.rpm-scripts FAILED for pacemaker-1.1.18-0.1.rc3.fc28.2 5 minutes ago https://taskotron.fedoraproject.org/artifacts/all/d0353112-ba22-11e7-8950-525400817a8f/task_output/rpmgrill.json    ( triggered by https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/53899 )
<fedora-notif> taskotron.result.new -- dist.rpmgrill NEEDS_INSPECTION for pacemaker-1.1.18-0.1.rc3.fc28.2 5 minutes ago https://taskotron.fedoraproject.org/artifacts/all/d0353112-ba22-11e7-8950-525400817a8f/task_output/rpmgrill.json    ( triggered by https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/53899 )
...
```
Problem 1: I should not be getting those, since only Askbot events should go through. By looking into ` fmn/fmn/rules/askbot.py` I don't really see what's wrong.

Problem 2: Even if I **disable** this filter, I'm still getting the messages. The only way to stop it is probably to delete that filter, or disable irc transport completely (that's what I did). Something seems very broken here.

**Comment by kparal** [comment] 2017-10-26 08:18
Not just taskotron results. I just received:
```
<fedora-notif> greenwave.greenwave.decision.update --  5 minutes ago     ( triggered by https://apps.fedoraproject.org/notifications/kparal.id.fedoraproject.org/irc/53899 )
```

**Comment by jeremycline** [comment] 2017-10-26 13:01
I've nearly completely re-written the backend for FMN in the latest release (2.0.0). As soon as https://pagure.io/fedora-infrastructure/issue/6466 is done I'll deploy it to staging and hopefully get it out right after the final freeze is over.

Sorry :(

Edit: in case you're interested in what the likely root cause is, FMN caches _everything_ from the database and it's likely that the cache is not properly invalidated.

**Comment by ryanlerch** [comment] 2023-02-27 03:19
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.

**Closed as completed by ryanlerch** 2023-02-27 03:19 UTC
Labels: fmn-old
