### ISSUE TITLE
continuous messages from fedora-notifs

### ISSUE THREAD

**Issue by carlwgeorge** [fedora-infra/fmn#162] opened 2017-01-25 20:39 UTC
I was attempting to start using the IRC notification feature.  I enabled it and added my nick.  Approximately 2-4 minutes later, the fedora-notifs bot started sending me messages about registration.  However, it kept sending them over and over again, about 50ish times per minute.  I tried to click one of the accept links, but it was scrolling so fast it caused me to accidentally click one of the reject links.  The registration messages kept coming, so I tried the accept link again, but it resulted in a 404.  Deleting my nick in the web app didn't make it stop.  Disabling the IRC delivery mechanism in the web app didn't make it stop.  I replied to the bot with "help", and eventually it returned the help text that showed me that I could reply with "stop", so I did that and it finally stopped.  I waited a few minutes, then tried to reproduce the problem, but it worked correctly this time, and I was able to register my nick without problems.  It was all very strange, and I understand this may be difficult to debug since I could not reproduce the issue, but I wanted to share the information just in case anyone has seen it before.

**Comment by jeremycline** [comment] 2017-02-23 12:48
I've been poking around FMN generally and I have a suspicion this was caused by the IRC backend placing a message in the database due to a netsplit, which then causes the digest producer to dispatch the message as a digest, which looks like it might call into the digest producer again?

I think that refactoring the IRC backend to make use of Twisted's core feature (deferring until network is ready for IO) rather than dumping the message in the database is the best way to solve this.

**Comment by ryanlerch** [comment] 2023-02-27 03:20
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.

**Closed as completed by ryanlerch** 2023-02-27 03:20 UTC
Labels: bug, fmn-old
