### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by nqb** [fedora-infra/fmn#276] opened 2018-02-13 05:37 UTC
Hello,

Recently, I created my FAS account (nqb) and started to configure notifications in https://apps.fedoraproject.org/notifications/.

I set up three confirmed e-mail addresses and enable "All release-monitoring.org events" filter.

At that time, I didn't receive any e-mails. On top of that, I verified mail.log on my mail server : there was no attempts to send me an e-mail from fedora-infra.

I don't know if this tracker is the place to open that case.

Could you please help me ?

**Comment by nqb** [comment] 2018-02-20 12:32
@relrod, @puiterwijk, @jeremycline : any idea about this issue ?

**Comment by jeremycline** [comment] 2018-03-26 14:04
People have reported not getting release-monitoring.org messages, but nothing obviously wrong jumps out at me. Messages are getting sent by anitya[0] and the "All release-monitoring.org events" rule matches that topic.

[0] https://apps.fedoraproject.org/datagrepper/raw?topic=org.release-monitoring.prod.anitya.project.version.update

**Comment by nqb** [comment] 2018-03-26 14:36
Hello Jeremy, 

In that case, how to help ?

**Comment by jeremycline** [comment] 2018-03-26 15:02
Hi @nqb,

You could see if you can replicate this in a development environment, but it could well be a problem with the production deployment so that might be a frustrating exercise. I'm no longer on the Fedora apps team so I don't devote a lot of time to maintaining FMN anymore. Investigating this is on my to-do list, but it's not terribly high on it I'm afraid.

**Comment by mattiaverga** [comment] 2018-04-01 14:53
@jeremycline maybe the problem is at line 218 in `fmn/lib/defaults.py`?
There it is declared to globally ignore all Anitya stuff with the `anitya_catchall` rule, if I'm not wrong.

**Comment by jeremycline** [comment] 2018-04-02 17:48
I looked at this with a fresh set of eyes and it looks like the fedmsg-hub service wasn't subscribing to ``org.release-monitoring`` messages. It's been fixed with http://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=f5d5e8e and it'll get pushed out in prod after the infrastructure freeze for the beta is over (Wednesday).

> @jeremycline maybe the problem is at line 218 in fmn/lib/defaults.py?
There it is declared to globally ignore all Anitya stuff with the anitya_catchall rule, if I'm not wrong.

@mattiaverga That could also be a problem if the match rule got added to an existing filter. I believe the way filters work is every rule in the filter must match, and at least one filter must match the message. @nqb, once the fix is pushed out, do make sure the rule is in a separate filter.

**Comment by mattiaverga** [comment] 2018-04-02 19:10
@jeremycline Yeah, I was wrong, the problem isn't in the default rules.
I've managed to bring up a local instance of fmn and after adding a new filter with the anitya_catchall rule (without deleting the default filters) I can successfully receive messages about anitya.
So, with the local instance messages are received, but with the same filters on fmn in prod they're not. I'm using the develop branch, maybe the problem has been resolved in some way after 2.0.2.

**Comment by jeremycline** [comment] 2018-04-02 19:26
Yeah, it was just the prod configuration for filtering incoming messages in the fedmsg consumer. I switched the staging instance to subscribe to release-monitoring messages and made sure it emailed me, so I think we can close this :smile:

**Closed as completed by jeremycline** 2018-04-02 19:26 UTC

**Comment by nqb** [comment] 2018-04-11 12:22
Hello @jeremycline, 

It works for me. Thanks !
