### ISSUE TITLE
FMN crash when editing list of projects to notify by email

### ISSUE THREAD

**Issue by zorun** [fedora-infra/fmn#227] opened 2017-09-02 06:22 UTC
On https://apps.fedoraproject.org/notifications/ I get a crash whenever I try to edit the list of projects for which I should be notified by email.

To reproduce:
- https://apps.fedoraproject.org/notifications/bjonglez.id.fedoraproject.org/email/50994/#
- click "edit" just below "projects" inside `Anything regarding a particular "upstream project"`
- add an upstream project to the list
- save

The service then crashes with "Internal Server Error" on https://apps.fedoraproject.org/notifications/api/argument

Apparently this is running 1.4.1 at the moment.

**Comment by jeremycline** [comment] 2017-09-12 13:52
Can you provide the entire entry you have for the upstream project list?

**Comment by zorun** [comment] 2017-09-12 19:18
Sure:

```
coq,babeld,libnatpmp,opendht,bdsync,erebus,archlinux-keyring,pius,bmon,confuse,horst,msgpack-cpp,pass,wireguard,asio,multipath-tcp,ring,mastodon,gplaycli,netsniff-ng,ansible,libevent,duniter,lxc,ipv6calc,restbed,argon2,ocaml,kea,gephi
```

I think the last one I tried to add is `radcli`

**Comment by jeremycline** [comment] 2017-09-12 19:23
Ah, I think I know what this is. For some reason, this is stored in the database as a JSON-encoded string in a field that has a length limit of 256 characters.

A rather silly workaround for your problem might be to start another filter and add additional projects there.

**Comment by zorun** [comment] 2017-09-18 20:19
Ah, I see...  I just started another filter and it indeed works.

On a possibly related note, I haven't received any email notification since 18th August.  Maybe I increased the number of watched projects so that the length was just under the limit for the frontend, but just above a similar limit for a backend process.  In any case, I reduced the number of watched projects in the first filter, let's see if I will now receive notifications...

**Comment by jeremycline** [comment] 2017-09-19 17:35
Interesting. I've heard of other people having trouble with the emails getting sent. The logs are very nearly useless at the moment so it's difficult to say what's going wrong. It does appear to be sending emails occasionally, but I can't tell if it is failing somewhere before that happens. I'm rewriting this to use a well-established task system rather than a home-grown one so I expect this will get fixed soon (or at least it will quickly become obvious what the problem is after that) as part of that.

Sorry 😞

**Comment by zorun** [comment] 2017-09-27 17:27
Ok, thanks :)  For the record, I still haven't received any notification email.

**Comment by zorun** [comment] 2018-04-07 11:28
I just received my first notification email in months \o/

Does that mean that this issue is being worked on?  In any case, it's great, thanks :)

**Comment by jeremycline** [comment] 2018-04-09 13:37
Yes, the anitya notifications got fixed recently. There's still not a fix for the original issue (the database column limit).

**Comment by ryanlerch** [comment] 2023-02-27 03:19
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.

**Closed as completed by ryanlerch** 2023-02-27 03:19 UTC
Labels: fmn-old
