### ISSUE TITLE
Missing "like-a-rock-updates-stable-iv" badge (or: missing fedmsg events for bodhi)

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#86] opened 2015-04-12 04:27 UTC
I initially wondered why I did not receive a "like-a-rock-updates-stable-iv" badge but the "received is-this-thing-on-updates-testing-iv" one a few weeks ago. I usually submit nearly every package to stable before pushing a new to testing (otherwise some packages like phpMyAdmin would only live in testing because they are releasing their updates quite often).

Thanks to @ralphbean there is this python script to check which updates are in testing (according to fedmsg) but not in stable:

```
#!/usr/bin/env python

# yum install python-requests python-arrow
import arrow
import requests

import collections

url = 'https://apps.fedoraproject.org/datagrepper/raw'
topics = [
    'org.fedoraproject.prod.bodhi.update.request.testing',
    'org.fedoraproject.prod.bodhi.update.request.stable',
]

def get_page(page, topic):
    print "getting page", page, "of", topic
    response = requests.get(url, params=dict(
        page=page,
        rows_per_page=100,
        topic=topic,
        user='robert',
    ))
    return response.json()

results = collections.defaultdict(list)

for topic in topics:
    data = get_page(page=1, topic=topic)
    total_pages = data['pages']
    for page in range(1, total_pages + 1):
        data = get_page(page=page, topic=topic)
        for msg in data['raw_messages']:
            title = msg['msg']['update']['title']
            results[topic].append((title, msg['timestamp']))


testing, stable = topics

stable_topics = [topic for topic, timestamp in results[stable]]
testing_topics = [topic for topic, timestamp in results[testing]]

print "-" * 20
for title, timestamp in results[testing]:
    if title not in stable_topics:
        print arrow.get(timestamp).humanize(), title, "is not in the stable list"

print "-" * 20
for title, timestamp in results[stable]:
    if title not in testing_topics:
        print arrow.get(timestamp).humanize(), title, "is not in the testing list"
```

However e.g. "phpMyAdmin-4.3.13-1.el7" is in stable (April 2015), "librsync-1.0.0-1.fc22" is in stable (March 2015). The oldest event is like "phpMyAdmin-3.5.6-1.el6" but in stable, too (February 2013) - just to name a few examples. Note that updates newer than 14 days might be really just in testing!

So, the question is why are there missing fedmsg events for bodhi. I understand that there might be a few ones, however in my case it seems like 100+ - hard to cross-check, because meanwhile retired Fedora versions are no longer listed in Bodhi (fortunately there is EPEL 5 as a reference).

My final question would be (if it has been verified that I am right): Can I get the missing "like-a-rock-updates-stable-iv" badge? ;-)

**Comment by ralphbean** [comment] 2015-04-12 14:23
I looked into this some last night but couldn't find any obvious cause in some of the frequent configuration errors (too few endpoints; firewall rules misconfigured, etc..).

I think the next step will be to tweak some of the reconnect parameters after the freeze is up and see if this keeps occurring.

**Comment by jeremycline** [comment] 2017-11-01 14:33
There's not much to be done for this issue on FMN (especially two years later) so I'm just going to close this.

**Closed as completed by jeremycline** 2017-11-01 14:33 UTC

**Comment by robert-scheck** [comment] 2017-11-01 17:07
Sad to see that there was no real result for 2+ years. Finally just closing is indeed a solution, but for me it's the easy one which personally gives me a bad taste about how exactly contributions are honored and valued (or not), especially when it comes to kind of statistics (in the end, badges are some fancy statistics to measure the community).

**Comment by jeremycline** [comment] 2017-11-01 18:11
Hi Robert,

It was not my intention to make light of the value of your contributions and I apologize for not being clearer in the note I left when closing this issue. This is not an issue with FMN since it merely receives fedmsgs and turns them into IRC or email notifications. It has nothing to do with recording/sending events, nor does it have any part of awarding badges.

There are several root causes for this sort of problem: Bodhi is (or was) mis-configured or had a bug that caused fedmsgs to not be sent, Bodhi sent the messages but no one received them (fedmsg uses ZeroMQ PUB/SUB sockets and there are no guarantees messages are received by anyone), or there is (or was) a bug in the badge awarding service.

You are more than welcome to open this issue against either [Bodhi](https://github.com/fedora-infra/bodhi/issues) or [Tahir](https://github.com/fedora-infra/tahrir/issues), but given the nature of fedmsg (no delivery guarantees) it's difficult to diagnose such a problem. @sayanchowdhury might also be able to provide some insight into what might be going wrong since he's the badges maintainer.

Once again, I'm sorry this has languished for several years.
