### ISSUE TITLE
Build notification - lack of information.

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/fmn#63] opened 2015-02-23 08:22 UTC
Notifications from Koji are now disabled but was providing useful information:
- changelog
- status, tag
- link to build RPM
- link to log

Notifications from FMN only provides minimal information

**Comment by remicollet** [comment] 2015-02-23 08:58
The most useful (for me) is the link to the build.log for failed tasks.

**Comment by ralphbean** [comment] 2015-02-23 15:38
Agreed.

TODO:
- [ ] Provide a msg2long_form implementation for koji builds.

**Comment by ralphbean** [comment] 2015-02-23 18:57
This is a duplicate of #54.  Working on it.

**Closed as completed by ralphbean** 2015-02-23 18:57 UTC
