### ISSUE TITLE
No notification for early failure

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fmn#62] opened 2015-02-23 08:20 UTC
I did not receive any notification from koji about this build failure:
http://koji.fedoraproject.org/koji/taskinfo?taskID=9035640

But I am also not seeing it in datagrepper:
https://apps.fedoraproject.org/datagrepper/raw/?user=pingou&category=buildsys

Are we missing a call somewhere?

**Comment by ralphbean** [comment] 2015-03-24 14:07
@pypingou can you duplicate this scenario?  I don't see what happened.

**Comment by pypingou** [comment] 2015-03-24 14:17
I don't remember seeing it since then. We wanted to check if we add all the ports correctly opened iirc (check if we had the same number of ports as threads)

**Comment by ralphbean** [comment] 2015-03-24 14:21
Hm, koji is exempt from that consideration I think.

https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/koji_hub/files/fedmsg-koji-plugin.py#n18

There, it is configured to connect over to the fedmsg-relay.. so it doesn't actually have any ports of its own.

**Comment by ralphbean** [comment] 2015-03-24 15:46
If it comes up again, please post here.  Not sure what can be done about this unless we can reproduce it.

**Comment by pypingou** [comment] 2015-03-24 15:47
sure, will do

**Comment by mizdebsk** [comment] 2015-07-09 20:25
I confirm this, so does #87. Reproducer: `stgkoji build --nowait rawhide 'git://xyzzy?#some-junk-here'`. This creates a [quickly failing task](http://koji.stg.fedoraproject.org/koji/taskinfo?taskID=90000763) which doesn't generate any fedmsg upon failure.

**Comment by ralphbean** [comment] 2015-07-09 20:29
So, this is a bug in koji itself (I think).  It's not even calling the fedmsg plugin on its side.  With that reproducer, we can probably make progress on this in the staging koji instance.

**Comment by jeremycline** [comment] 2016-11-30 17:12
I'm going to close this since it doesn't seem to be a bug in FMN. Feel free to re-open it if that's not the case!

**Closed as completed by jeremycline** 2016-11-30 17:12 UTC
