### ISSUE TITLE
"triggered by" annotations are not appended

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#109] opened 2015-12-10 09:48 UTC
I have the following enabled:

> We can annotate your messages with a "triggered by" link that will let you know which filter was responsible for triggering each message. This can be useful if you are actively tuning your profile, or even if you just want to track down why you're getting certain messages. On the other hand, some people find it annoying to have extra links tacked onto their messages. It's up to you...

However, there are no "triggered by" links appended to the IRC messages I receive:

```
<fedora-notifs> taskotron.result.new -- rpmlint PASSED for php-pecl-http-2.5.5-1.fc23 2 minutes ago https://taskotron.fedoraproject.org/artifacts/all/ac239924-9cf8-11e5-934e-52540053ee00/task_output/php-pecl-http-2.5.5-1.fc23.log
<fedora-notifs> planet.post.new -- renault posted "Compte rendu des JM2L 2015" 3 minutes ago http://blog.fedora-fr.org/renault/post/Compte-rendu-des-JM2L-2015
<fedora-notifs> infragit.receive -- adamwill pushed a commit to the fedora-infra ansible repo (master):  "openqa: always fully re-load the test templates (..more)" 2 minutes ago https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?h=master&id=7e2b87f99a63886baa2292a45ff8e23d7dcaeac6
<fedora-notifs> mkrizek kicked off 2 rebuilds of the taskotron copr 2 minutes ago https://copr.fedoraproject.org/coprs/tflink/taskotron/
<fedora-notifs> trac.ticket.update -- adrian updated a ticket on the Fedora Infrastructure trac instance 2 minutes ago https://fedorahosted.org/fedora-infrastructure/ticket/5016
```

**Comment by pypingou** [comment] 2015-12-10 10:06
wfm, could it be a setting to check in the UI?

```
10:48:10 fedora-notifs | kparal opened issue #109 on fedora-infra/fmn: "triggered by" annotations are not appended seconds ago https://github.com/fedora-infra/fmn/issues/109    ( triggered by
                       | https://apps.fedoraproject.org/notifications/pingou.id.fedoraproject.org/irc/20507 )
```

**Comment by kparal** [comment] 2015-12-10 10:10
Sorry, what is the question? When I look into settings, it says I have it enabled:

>  I'm configured right now to append those links.

I have tried to disable and enable it again, it didn't help.

For the other settings, I have links shortening disabled and message markup enabled. Maybe they can influence it somehow?

**Comment by kparal** [comment] 2016-02-03 08:14
Unfortunately this is still happening, no "triggered by" links for me.

**Comment by pypingou** [comment] 2016-02-03 09:25
A totaly crazy idea, but did you try with another IRC client?

**Comment by kparal** [comment] 2016-02-03 12:39
I'm using Hexchat, and it used to work before. I tried Xchat as well, no change. I also tried email, and I'm not receiving it in email either. This is what I just received by email:

```
Kparal made a wiki edit to "User:Kparal/tmp"
        https://fedoraproject.org/w/index.php?title=User:Kparal/tmp&diff=prev&oldid=433543
```

That's all, no other text. What can I do to debug this more?

**Comment by pypingou** [comment] 2016-02-03 13:04
On Wed, Feb 03, 2016 at 04:39:51AM -0800, Kamil Páral wrote:

>    I'm using Hexchat, and it used to work before. I tried Xchat as well, no
>    change. I also tried email, and I'm not receiving it in email either. This
>    is what I just received by email:

If it's also occurring by email, could you send us one of them so that we can
inspect the headers?

Thanks

**Comment by kparal** [comment] 2016-02-03 13:08
Here we go :)

```
Return-Path: notifications@fedoraproject.org
Received: from zmta02.collab.prod.int.phx2.redhat.com (LHLO
 zmta02.collab.prod.int.phx2.redhat.com) (10.5.81.9) by
 zmail17.collab.prod.int.phx2.redhat.com with LMTP; Wed, 3 Feb 2016 07:31:07
 -0500 (EST)
Received: from int-mx11.intmail.prod.int.phx2.redhat.com (int-mx11.intmail.prod.int.phx2.redhat.com [10.5.11.24])
    by zmta02.collab.prod.int.phx2.redhat.com (Postfix) with ESMTP id 4214B122938
    for <kparal@mail.corp.redhat.com>; Wed,  3 Feb 2016 07:31:07 -0500 (EST)
Received: from mx1.redhat.com (ext-mx07.extmail.prod.ext.phx2.redhat.com [10.5.110.31])
    by int-mx11.intmail.prod.int.phx2.redhat.com (8.14.4/8.14.4) with ESMTP id u13CV7Vl024759
    (version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-GCM-SHA384 bits=256 verify=NO)
    for <kparal@redhat.com>; Wed, 3 Feb 2016 07:31:07 -0500
Received: from bastion.fedoraproject.org (bastion01.phx2.fedoraproject.org [10.5.126.12])
    by mx1.redhat.com (Postfix) with ESMTP id 59908C0A524C
    for <kparal@redhat.com>; Wed,  3 Feb 2016 12:31:06 +0000 (UTC)
Received: from notifs-backend01.phx2.fedoraproject.org (notifs-backend01.phx2.fedoraproject.org [10.5.126.168])
    by bastion01.phx2.fedoraproject.org (Postfix) with ESMTP id 2E735606E612
    for <kparal@redhat.com>; Wed,  3 Feb 2016 12:31:06 +0000 (UTC)
To: kparal@redhat.com
From: notifications@fedoraproject.org
X-Fedmsg-Topic: org.fedoraproject.prod.wiki.article.edit
X-Fedmsg-Category: wiki
X-Fedmsg-Username: kparal
Subject: Kparal made a wiki edit to "User:Kparal/tmp"
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Message-Id: <20160203123106.2E735606E612@bastion01.phx2.fedoraproject.org>
Date: Wed,  3 Feb 2016 12:31:06 +0000 (UTC)
X-RedHat-Spam-Score: -0.638  (ALL_TRUSTED,BAYES_50,RP_MATCHES_RCVD) 10.5.126.12 bastion01.phx2.fedoraproject.org 10.5.126.12 bastion01.phx2.fedoraproject.org <notifications@fedoraproject.org>
X-Scanned-By: MIMEDefang 2.68 on 10.5.11.24
X-Scanned-By: MIMEDefang 2.78 on 10.5.110.31

S3BhcmFsIG1hZGUgYSB3aWtpIGVkaXQgdG8gIlVzZXI6S3BhcmFsL3RtcCIKCWh0dHBzOi8vZmVk
b3JhcHJvamVjdC5vcmcvdy9pbmRleC5waHA/dGl0bGU9VXNlcjpLcGFyYWwvdG1wJmRpZmY9cHJl
diZvbGRpZD00MzM1NDM=
```

**Comment by kparal** [comment] 2016-02-25 08:23
I don't know what changed, but I started getting "triggered by" links. The only thing that could affect this that I know of is that I logged into staging FMN and played with it a bit. Not sure if it can be related.

**Comment by jeremycline** [comment] 2016-11-30 17:41
Since it sounds like there was no root cause found and this started working, I'm going to close this. Please re-open this if it's still a problem

**Closed as completed by jeremycline** 2016-11-30 17:41 UTC
