### ISSUE TITLE
batched notifications sometimes have blank entries and count "weirdly"

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/fmn#298] opened 2018-06-11 21:37 UTC
I have fmn set to send me e-mail summaries once a day, or every 50 notifications. On Saturday there were enough notifications to trigger a few e-mails. The first one seemed pretty normal, and sent 50 as expected. The second one sent several with blank lines, and then also counted up to 53:

```
Digest Summary:
1.	bowlofeggs pushed 1 commit to rpms/ejabberd (master)
2.	bowlofeggs's erlang-fast_tls-1.0.22-1.fc29 completed
3.	
4.	bowlofeggs pushed 1 commit to rpms/erlang-fast_xml (master)
5.	pleasedont@spam.me updated 'cf_fixed_in' on RHBZ#1571777 'erlang-fast_tls-1.0.22 is available'
6.	bowlofeggs's erlang-stun-1.0.22-1.fc29 completed
7.	
8.	pleasedont@spam.me updated 'status' and 'cf_fixed_in' on RHBZ#1571790 'erlang-stun-1.0.22 is available'
9.	bowlofeggs's erlang-fast_xml-1.1.30-1.fc29 completed
10.	
11.	pleasedont@spam.me updated 'cf_fixed_in' on RHBZ#1571779 'erlang-fast_xml-1.1.30 is available'
12.	bowlofeggs's erlang-fast_yaml-1.0.14-1.fc29 completed
13.	
14.	bowlofeggs's erlang-esip-1.0.23-1.fc29 completed
15.	
16.	bowlofeggs's erlang-p1_oauth2-0.6.3-1.fc29 completed
17.	
18.	bowlofeggs's erlang-xmpp-1.1.21-1.fc29 completed
19.	
20.	pleasedont@spam.me updated 'cf_fixed_in' on RHBZ#1571780 'erlang-fast_yaml-1.0.14 is available'
21.	bowlofeggs's erlang-eimp-1.0.5-1.fc29 completed
22.	
23.	pleasedont@spam.me updated 'cf_fixed_in' on RHBZ#1578365 'erlang-esip-1.0.23 is available'
24.	pleasedont@spam.me updated 'status' and 'cf_fixed_in' on RHBZ#1572011 'erlang-p1_oauth2-0.6.3 is available'
25.	pleasedont@spam.me updated 'status' and 'cf_fixed_in' on RHBZ#1571795 'erlang-xmpp-1.1.21 is available'
26.	pleasedont@spam.me updated 'cf_fixed_in' on RHBZ#1561272 'erlang-eimp-1.0.5 is available'
27.	bowlofeggs's ejabberd-18.04-2.fc29 completed
28.	
29.	pleasedont@spam.me updated 'cf_fixed_in' on RHBZ#1571775 'ejabberd-18.04 is available'
30.	bowlofeggs pushed 1 commit to rpms/erlang-fast_tls (f28)
31.	bowlofeggs's erlang-fast_tls-1.0.22-1.fc28 completed
32.	
33.	kevin pushed to python3-py3dns (master).  "Add patch to change now reserved async keyword to py3async. Fixes bug #1583688"
34.	pleasedont@spam.him commented on RHBZ#1583688 'python3-py3dns FTBFS on python 3.7'
35.	kevin's python3-py3dns-3.1.1-6.fc29 completed
36.	ralph's python-moksha-hub-1.5.9-1.el7 bodhi update completed push to testing
37.	bowlofeggs pushed 1 commit to rpms/erlang-fast_xml (f28)
38.	bowlofeggs pushed 1 commit to rpms/erlang-fast_xml (master)
39.	bowlofeggs pushed 1 commit to rpms/erlang-stun (f28)
40.	bowlofeggs's erlang-fast_xml-1.1.30-1.fc28 completed
41.	
42.	bowlofeggs's erlang-stun-1.0.22-1.fc28 completed
43.	
44.	bowlofeggs pushed 1 commit to rpms/erlang-esip (f28)
45.	bowlofeggs pushed 1 commit to rpms/erlang-fast_yaml (f28)
46.	bowlofeggs pushed 1 commit to rpms/erlang-p1_oauth2 (f28)
47.	bowlofeggs pushed 1 commit to rpms/erlang-xmpp (f28)
48.	bowlofeggs's erlang-fast_yaml-1.0.14-1.fc28 completed
49.	
50.	bowlofeggs's erlang-esip-1.0.23-1.fc28 completed
51.	bowlofeggs's erlang-eimp-1.0.5-1.fc28 completed
52.	
53.	
```

**Comment by mattiaverga** [comment] 2018-06-13 16:20
I think whitelines are caused by these messages:
https://apps.fedoraproject.org/datagrepper/raw?topic=org.centos.prod.ci.pipeline.allpackages-build.package.ignored
For example line 3 in the above digest seems to be https://apps.fedoraproject.org/datagrepper/id?id=2018-3bb9f693-5d51-4381-9042-27a2b6f02a12&is_raw=true&size=extra-large

**Comment by QuLogic** [comment] 2019-06-04 05:25
I also get Jenkins ones, but it looks like I'm now getting new empty ones from Bodhi too.

**Comment by ryanlerch** [comment] 2023-02-27 03:13
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.

**Closed as completed by ryanlerch** 2023-02-27 03:13 UTC
Labels: bug, fmn-old
